title: <p align="center"> Vennesh </p>
logo: /assets/img/logo.jpg
description: <p align="center">|
  <a href="https://www.linkedin.com/in/vennesh-k-he-him-his-388901105">LinkedIn</a> |
  <a href="https://github.com/vennesh">GitHub</a>
  
  <br>   
  I'm working on Java,Angular projects
  <br>
  </p>
theme: jekyll-theme-minimal
